-- =====================================================================
-- El Juanse Bazar · Datos de demostración (FICTICIOS)
-- Ejecutar después de 0001_esquema.sql. Se pueden borrar desde el panel.
-- =====================================================================

insert into public.settings (id, business_name, tagline, whatsapp, hours, instagram, facebook, site_url, show_prices, design) values
  (1, 'El Juanse Bazar', 'Bazar a medida', '5491126763257', 'Lun a vie 9 a 19 h · Sáb 9 a 14 h', '@eljuansebazar', 'El Juanse Bazar', '', false, '{"heroEyebrow": "Bazar a medida", "heroTitle": "Todo para tu cocina y tu casa, en un solo lugar", "heroText": "Vajilla, organización, deco y artículos de bazar para tu casa o tu empresa, con la opción de personalizarlos con tu logo. Mirá el catálogo y pedinos una cotización por WhatsApp.", "heroCta": "Ver catálogo", "heroProducts": ["V003", "O014", "D001"], "promoTitle": "Semana del bazar", "promoText": "Precios especiales en vajilla y organización hasta agotar stock.", "waTitle": "¿No encontrás lo que buscás?", "waText": "Tenemos más artículos de los que ves en la web. Escribinos con una foto o una idea y te decimos si lo conseguimos.", "customEyebrow": "Regalos empresariales", "customTitle": "Tu marca, en los productos que la gente usa todos los días", "customText": "Personalizamos tazas, vasos, tablas, frascos y más con el logo de tu empresa. Ideal para regalos de fin de año, eventos, kits de bienvenida y merchandising."}'::jsonb)
on conflict (id) do nothing;

insert into public.categories (slug, name, position, active, is_offers) values
  ('cocina', 'Cocina', 0, true, false),
  ('vajilla', 'Vajilla', 1, true, false),
  ('decoracion', 'Decoración', 2, true, false),
  ('organizacion', 'Organización', 3, true, false),
  ('bano', 'Baño', 4, true, false),
  ('limpieza', 'Limpieza', 5, true, false),
  ('accesorios-para-el-hogar', 'Accesorios para el hogar', 6, true, false),
  ('ofertas', 'Ofertas', 7, true, true);

insert into public.products (sku, slug, name, category_id, description, materials, dimensions, variants, price, old_price, availability, stock, tag, featured, placeholder, created_at) values
  ('C001', 'sarten-antiadherente-24-cm', 'Sartén antiadherente 24 cm', (select id from public.categories where slug='cocina'), 'Sartén de aluminio forjado con recubrimiento antiadherente de tres capas. Apta para todo tipo de cocinas, incluida inducción.', 'Aluminio forjado, mango de baquelita', '24 cm de diámetro · 4,5 cm de alto', array['Grafito','Arena']::text[], 28900, null, 'disponible', 12, 'destacado', true, '{"kind": "pan", "color": "#4A4642", "bg": "#E9E2D6"}'::jsonb, '2026-09-02 12:00:00-03'),
  ('C002', 'set-de-utensilios-de-silicona-x5', 'Set de utensilios de silicona x5', (select id from public.categories where slug='cocina'), 'Cuchara, espátula, cucharón, espumadera y pinza con cabo de madera. No rayan las ollas antiadherentes.', 'Silicona alimentaria, madera de haya', 'Largo 30 cm aprox.', array['Verde salvia','Gris','Terracota']::text[], 15400, null, 'disponible', 20, 'nuevo', false, '{"kind": "utensils", "color": "#8FA38A", "bg": "#EEE9DF"}'::jsonb, '2026-10-01 12:00:00-03'),
  ('C003', 'tabla-de-madera-de-paraiso-40x25', 'Tabla de madera de paraíso 40x25', (select id from public.categories where slug='cocina'), 'Tabla maciza para picar y servir, con agujero para colgar. Terminación con aceite mineral.', 'Madera de paraíso', '40 x 25 x 2 cm', '{}'::text[], 12800, null, 'disponible', 9, '', true, '{"kind": "board", "color": "#B8895B", "bg": "#EFE7DA"}'::jsonb, '2026-08-20 12:00:00-03'),
  ('C004', 'olla-de-acero-inoxidable-20-cm', 'Olla de acero inoxidable 20 cm', (select id from public.categories where slug='cocina'), 'Olla con fondo difusor triple y tapa de acero. Capacidad 4,5 litros.', 'Acero inoxidable 18/10', '20 cm de diámetro · 4,5 L', '{}'::text[], 46500, null, 'consultar', 0, '', false, '{"kind": "pot", "color": "#A9ADB0", "bg": "#E7E4DE"}'::jsonb, '2026-07-11 12:00:00-03'),
  ('C005', 'frascos-hermeticos-x3', 'Frascos herméticos x3', (select id from public.categories where slug='cocina'), 'Juego de tres frascos de vidrio con tapa de bambú y burlete de silicona. Ideales para legumbres, café o yerba.', 'Vidrio borosilicato, bambú', '500 ml, 800 ml y 1,2 L', '{}'::text[], 13900, 16900, 'disponible', 15, 'oferta', false, '{"kind": "jar", "color": "#C9D6D2", "bg": "#EAE5DA"}'::jsonb, '2026-09-14 12:00:00-03'),
  ('C006', 'rallador-de-4-caras', 'Rallador de 4 caras', (select id from public.categories where slug='cocina'), 'Rallador de acero con cuatro filos distintos y base antideslizante.', 'Acero inoxidable, base plástica', '23 cm de alto', '{}'::text[], 7200, null, 'disponible', 25, '', false, '{"kind": "grater", "color": "#B4B7B8", "bg": "#ECE8E1"}'::jsonb, '2026-06-30 12:00:00-03'),
  ('V001', 'set-de-vasos-x6', 'Set de vasos x6', (select id from public.categories where slug='vajilla'), 'Vasos de vidrio templado de paredes rectas, aptos lavavajillas. Uso diario.', 'Vidrio templado', '350 ml · 11 cm de alto', array['Transparente','Ámbar']::text[], 16800, null, 'disponible', 18, 'destacado', true, '{"kind": "glass", "color": "#B9CEC8", "bg": "#E8E2D7"}'::jsonb, '2026-09-20 12:00:00-03'),
  ('V002', 'plato-playo-de-gres-27-cm', 'Plato playo de gres 27 cm', (select id from public.categories where slug='vajilla'), 'Plato de gres esmaltado a mano, con borde crudo. Cada pieza varía levemente en tono.', 'Gres esmaltado', '27 cm de diámetro', array['Arena','Azul enlozado','Blanco tiza']::text[], 8900, 10500, 'disponible', 40, 'oferta', false, '{"kind": "plate", "color": "#D9CFC0", "bg": "#ECE6DC"}'::jsonb, '2026-08-05 12:00:00-03'),
  ('V003', 'taza-de-ceramica-esmaltada-350-ml', 'Taza de cerámica esmaltada 350 ml', (select id from public.categories where slug='vajilla'), 'Taza grande con asa amplia y esmalte de efecto reactivo. Apta microondas.', 'Cerámica esmaltada', '350 ml · 9,5 cm de alto', array['Azul','Crema','Verde oliva']::text[], 6900, null, 'disponible', 30, 'nuevo', true, '{"kind": "mug", "color": "#5B74A6", "bg": "#EDE6D9"}'::jsonb, '2026-10-03 12:00:00-03'),
  ('V004', 'set-de-copas-x4', 'Set de copas x4', (select id from public.categories where slug='vajilla'), 'Copas de vino de cristalino con tallo fino. Presentación en caja.', 'Cristalino sin plomo', '450 ml · 21 cm de alto', '{}'::text[], 21500, 25900, 'disponible', 7, 'oferta', false, '{"kind": "wineglass", "color": "#C8D3D6", "bg": "#E6E1D8"}'::jsonb, '2026-07-28 12:00:00-03'),
  ('V005', 'bowl-de-ceramica-15-cm', 'Bowl de cerámica 15 cm', (select id from public.categories where slug='vajilla'), 'Bowl para desayunos, sopas o ensaladas individuales. Interior liso y exterior texturado.', 'Cerámica', '15 cm de diámetro · 7 cm de alto', array['Crema','Gris piedra']::text[], 5900, null, 'sin_stock', 0, '', false, '{"kind": "bowl", "color": "#C7BBA8", "bg": "#EEE8DE"}'::jsonb, '2026-06-18 12:00:00-03'),
  ('D001', 'florero-de-vidrio-soplado', 'Florero de vidrio soplado', (select id from public.categories where slug='decoracion'), 'Florero de vidrio soplado con forma orgánica. Cada pieza es única.', 'Vidrio soplado', '28 cm de alto', array['Verde agua','Humo']::text[], 18700, null, 'disponible', 5, 'destacado', true, '{"kind": "vase", "color": "#9FBDB2", "bg": "#E9E3D8"}'::jsonb, '2026-09-10 12:00:00-03'),
  ('D002', 'vela-aromatica-en-frasco', 'Vela aromática en frasco', (select id from public.categories where slug='decoracion'), 'Vela de cera de soja en frasco de vidrio. Duración aproximada de 40 horas.', 'Cera de soja, vidrio', '8 x 10 cm · 220 g', array['Vainilla','Lavanda','Higo']::text[], 9800, null, 'disponible', 22, 'nuevo', false, '{"kind": "candle", "color": "#D8C7A6", "bg": "#EDE7DD"}'::jsonb, '2026-09-29 12:00:00-03'),
  ('D003', 'maceta-de-ceramica-14-cm', 'Maceta de cerámica 14 cm', (select id from public.categories where slug='decoracion'), 'Maceta con plato incorporado y orificio de drenaje.', 'Cerámica esmaltada', '14 cm de diámetro · 13 cm de alto', array['Blanco','Terracota','Negro mate']::text[], 8400, null, 'disponible', 16, '', false, '{"kind": "planter", "color": "#E4DED3", "bg": "#E6DFD2"}'::jsonb, '2026-08-12 12:00:00-03'),
  ('D004', 'portarretrato-de-madera-13x18', 'Portarretrato de madera 13x18', (select id from public.categories where slug='decoracion'), 'Portarretrato de madera natural con vidrio y pie trasero. Se puede colgar.', 'Madera de pino, vidrio', 'Foto 13 x 18 cm', array['Natural','Negro']::text[], 7600, null, 'consultar', 0, '', false, '{"kind": "frame", "color": "#C29C6E", "bg": "#ECE7DF"}'::jsonb, '2026-05-22 12:00:00-03'),
  ('O014', 'organizador-de-cocina', 'Organizador de cocina', (select id from public.categories where slug='organizacion'), 'Organizador apilable con tres divisiones extraíbles para alacenas y bajo mesada.', 'Polipropileno libre de BPA', '36 x 26 x 12 cm', array['Blanco','Gris']::text[], 19900, null, 'disponible', 14, 'destacado', true, '{"kind": "box", "color": "#E9E6E0", "bg": "#DCD5C8"}'::jsonb, '2026-09-25 12:00:00-03'),
  ('O002', 'canasto-de-seagrass', 'Canasto de seagrass', (select id from public.categories where slug='organizacion'), 'Canasto tejido a mano con manijas, para mantas, juguetes o ropa.', 'Fibra de seagrass', '35 cm de diámetro · 30 cm de alto', '{}'::text[], 16200, null, 'disponible', 8, '', false, '{"kind": "basket", "color": "#B99B6B", "bg": "#EEE8DD"}'::jsonb, '2026-08-30 12:00:00-03'),
  ('O003', 'caja-organizadora-12-l', 'Caja organizadora 12 L', (select id from public.categories where slug='organizacion'), 'Caja con tapa y traba lateral. Apilable y transparente para ver el contenido.', 'Polipropileno', '40 x 28 x 16 cm · 12 L', '{}'::text[], 9300, 11200, 'disponible', 35, 'oferta', false, '{"kind": "box", "color": "#CFD8DA", "bg": "#E9E4DA"}'::jsonb, '2026-07-04 12:00:00-03'),
  ('O004', 'especiero-giratorio', 'Especiero giratorio', (select id from public.categories where slug='organizacion'), 'Especiero de 360° con 12 frascos de vidrio y etiquetas incluidas.', 'Acero, vidrio, bambú', '20 cm de diámetro · 28 cm de alto', '{}'::text[], 24600, null, 'disponible', 6, 'nuevo', false, '{"kind": "spice", "color": "#A88B67", "bg": "#ECE6DA"}'::jsonb, '2026-10-05 12:00:00-03'),
  ('B001', 'set-de-bano-3-piezas', 'Set de baño 3 piezas', (select id from public.categories where slug='bano'), 'Dispenser, vaso y jabonera de cerámica con terminación mate.', 'Cerámica', 'Dispenser 18 cm de alto', array['Blanco','Gris piedra']::text[], 17500, null, 'disponible', 10, '', false, '{"kind": "bottle", "color": "#D7D2C9", "bg": "#E5DFD4"}'::jsonb, '2026-08-08 12:00:00-03'),
  ('B002', 'toalla-de-algodon-70x140', 'Toalla de algodón 70x140', (select id from public.categories where slug='bano'), 'Toalla de baño de 500 g/m², suave y de secado rápido.', 'Algodón 100%', '70 x 140 cm · 500 g/m²', array['Arena','Blanco','Gris']::text[], 13200, null, 'disponible', 28, '', false, '{"kind": "towel", "color": "#D4C3A8", "bg": "#ECE7DE"}'::jsonb, '2026-07-19 12:00:00-03'),
  ('B003', 'dispenser-de-jabon-de-vidrio', 'Dispenser de jabón de vidrio', (select id from public.categories where slug='bano'), 'Dispenser de vidrio grueso con válvula de acero. Para jabón líquido o detergente.', 'Vidrio, acero inoxidable', '400 ml', array['Ámbar','Transparente']::text[], 6800, null, 'disponible', 19, '', false, '{"kind": "bottle", "color": "#B7834A", "bg": "#EDE8DF"}'::jsonb, '2026-09-01 12:00:00-03'),
  ('L001', 'escobillon-de-fibra', 'Escobillón de fibra', (select id from public.categories where slug='limpieza'), 'Escobillón de fibra sintética con cabo de madera de 1,20 m.', 'Fibra sintética, madera', 'Cepillo 30 cm · cabo 120 cm', '{}'::text[], 5400, null, 'disponible', 30, '', false, '{"kind": "broom", "color": "#55606A", "bg": "#ECE6DC"}'::jsonb, '2026-06-10 12:00:00-03'),
  ('L002', 'balde-plegable-10-l', 'Balde plegable 10 L', (select id from public.categories where slug='limpieza'), 'Balde de silicona plegable con manija rígida. Se guarda en 5 cm.', 'Silicona, polipropileno', '10 L · plegado 5 cm de alto', array['Gris','Azul']::text[], 8700, null, 'disponible', 12, 'nuevo', false, '{"kind": "bucket", "color": "#7C8C9C", "bg": "#E8E3D9"}'::jsonb, '2026-10-06 12:00:00-03'),
  ('L003', 'panos-de-microfibra-x3', 'Paños de microfibra x3', (select id from public.categories where slug='limpieza'), 'Paños de microfibra para vidrios, cocina y superficies delicadas.', 'Microfibra', '40 x 40 cm', '{}'::text[], 4200, null, 'sin_stock', 0, '', false, '{"kind": "towel", "color": "#A8B9C9", "bg": "#EDE8E0"}'::jsonb, '2026-05-30 12:00:00-03'),
  ('A001', 'mantel-antimanchas-140x180', 'Mantel antimanchas 140x180', (select id from public.categories where slug='accesorios-para-el-hogar'), 'Mantel de tela con tratamiento antimanchas. Se limpia con un paño húmedo.', 'Poliéster con tratamiento', '140 x 180 cm', array['Lino natural','Gris']::text[], 22400, null, 'disponible', 9, '', false, '{"kind": "towel", "color": "#C9BCA6", "bg": "#E6E0D5"}'::jsonb, '2026-08-16 12:00:00-03'),
  ('A002', 'perchero-de-pie', 'Perchero de pie', (select id from public.categories where slug='accesorios-para-el-hogar'), 'Perchero de madera maciza con ocho ganchos y base de trípode.', 'Madera de eucalipto', '175 cm de alto', '{}'::text[], 38900, null, 'consultar', 0, '', false, '{"kind": "rack", "color": "#9C7A55", "bg": "#EDE8E0"}'::jsonb, '2026-07-01 12:00:00-03'),
  ('A003', 'individuales-de-yute-x4', 'Individuales de yute x4', (select id from public.categories where slug='accesorios-para-el-hogar'), 'Individuales redondos de yute tejido, con borde reforzado.', 'Yute natural', '38 cm de diámetro', '{}'::text[], 11600, 13900, 'disponible', 20, 'oferta', false, '{"kind": "mat", "color": "#C2A57A", "bg": "#E8E2D7"}'::jsonb, '2026-09-05 12:00:00-03');

insert into public.faqs (question, answer, position) values
  ('¿Hay un mínimo de compra?', 'Para compras de productos del catálogo no hay mínimo. Para productos personalizados con logo, el mínimo depende del artículo y la técnica: en general desde 12 unidades.', 0),
  ('¿Cuánto tarda la producción de un pedido personalizado?', 'Entre 7 y 15 días hábiles desde que aprobás el boceto y se confirma el pedido. En fechas de alta demanda, como fin de año, conviene consultar con más anticipación.', 1),
  ('¿Cuánto tarda la entrega?', 'Los productos con stock se despachan dentro de las 48 h hábiles de confirmado el pago. El tiempo de viaje depende de la zona y del transporte elegido.', 2),
  ('¿Hacen envíos a todo el país?', 'Sí, enviamos a todo el país por correo o transporte. En CABA y GBA también coordinamos envíos en moto. El costo se calcula según destino, peso y volumen.', 3),
  ('¿Qué formas de pago aceptan?', 'Transferencia bancaria y Mercado Pago. Para empresas emitimos factura A o B. Las compras no se pagan en la web: coordinamos todo por WhatsApp.', 4),
  ('¿Cómo hago un pedido?', 'Agregá los productos a tu lista de consulta y envianosla por WhatsApp. Te confirmamos stock, precio final y costo de envío, y te pasamos los datos de pago.', 5);

-- Trabajos personalizados de ejemplo (marcas inventadas). Reemplazar por fotos reales desde el panel.
insert into public.custom_works (title, technique, quantity, placeholder, position) values
  ('Café Norte', 'Sublimación', '60 u.', '{"brand": "Café Norte", "mark": "circle", "kind": "mug", "color": "#F1ECE3", "bg": "#DCD3C4", "ink": "#3B2A20"}'::jsonb, 0),
  ('Estudio Lumen', 'Grabado láser', '25 u.', '{"brand": "Estudio Lumen", "mark": "square", "kind": "board", "color": "#C49668", "bg": "#EAE3D6", "ink": "#6B4A2B"}'::jsonb, 1),
  ('Grupo Andes', 'Serigrafía', '120 u.', '{"brand": "Grupo Andes", "mark": "triangle", "kind": "glass", "color": "#C9D8D3", "bg": "#E5DED1", "ink": "#2E3A35"}'::jsonb, 2),
  ('Huerta Viva', 'Etiqueta y tapa grabada', '40 u.', '{"brand": "Huerta Viva", "mark": "leaf", "kind": "jar", "color": "#D3DDD8", "bg": "#EDE6DA", "ink": "#3E5A3A"}'::jsonb, 3);
